/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.regex.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pooja
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLab = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstnamelabel = new javax.swing.JLabel();
        firstnametextfield = new javax.swing.JTextField();
        lastnamelabel = new javax.swing.JLabel();
        lastnametextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        agetextfield = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        messagelabel = new javax.swing.JLabel();
        messagetexta = new javax.swing.JScrollPane();
        messagetextarea = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        ageELabel = new javax.swing.JLabel();
        emailELabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLab.setBackground(new java.awt.Color(204, 204, 255));

        titleLabel.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        titleLabel.setText("CUSTOMER REGISTRATION");

        firstnamelabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        firstnamelabel.setText("First Name");

        firstnametextfield.setBackground(new java.awt.Color(255, 255, 204));
        firstnametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametextfieldActionPerformed(evt);
            }
        });

        lastnamelabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lastnamelabel.setText("Last Name");

        lastnametextfield.setBackground(new java.awt.Color(255, 255, 204));
        lastnametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametextfieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Age");

        agetextfield.setBackground(new java.awt.Color(255, 255, 204));
        agetextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetextfieldActionPerformed(evt);
            }
        });
        agetextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                agetextfieldKeyReleased(evt);
            }
        });

        emaillabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        emaillabel.setText("Email");

        messagelabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        messagelabel.setText("Message");

        messagetextarea.setBackground(new java.awt.Color(255, 255, 204));
        messagetextarea.setColumns(20);
        messagetextarea.setRows(5);
        messagetexta.setViewportView(messagetextarea);

        submit.setBackground(new java.awt.Color(255, 255, 204));
        submit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        EmailTextField.setBackground(new java.awt.Color(255, 255, 204));
        EmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout titleLabLayout = new javax.swing.GroupLayout(titleLab);
        titleLab.setLayout(titleLabLayout);
        titleLabLayout.setHorizontalGroup(
            titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLabLayout.createSequentialGroup()
                .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(titleLabel))
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(titleLabLayout.createSequentialGroup()
                                    .addComponent(lastnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(34, 34, 34))
                                .addComponent(jLabel1)
                                .addComponent(messagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstnametextfield)
                            .addComponent(messagetexta)
                            .addComponent(agetextfield)
                            .addComponent(lastnametextfield)
                            .addComponent(EmailTextField))
                        .addGap(20, 20, 20)
                        .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ageELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        titleLabLayout.setVerticalGroup(
            titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(firstnametextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(firstnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(titleLabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agetextfield))
                            .addGroup(titleLabLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lastnamelabel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))))
                .addGap(18, 18, 18)
                .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailELabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(titleLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(messagetexta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titleLabLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(messagelabel)))
                .addGap(35, 35, 35)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametextfieldActionPerformed

    private void lastnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametextfieldActionPerformed

    private void agetextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetextfieldActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
String firstname=firstnametextfield.getText();
String lastname=lastnametextfield.getText();
String age=agetextfield.getText();
String email=EmailTextField.getText();
String message=messagetextarea.getText();
String title="Customer Information";
if(firstname.equals("")||lastname.equals("")||age.equals("")||email.equals("")||message.equals(""))
      {
          JOptionPane.showMessageDialog(null, "Please enter all the fields");
      }
      else{
            ImageIcon icon = new ImageIcon("C:\\Users\\pooja\\OneDrive\\Desktop\\imageicon.png");
      JOptionPane.showMessageDialog(this, firstname+" "+lastname+" "+age+" "+email+" "+message, title,JOptionPane.INFORMATION_MESSAGE,icon);
      }               
    }//GEN-LAST:event_submitActionPerformed

    private void agetextfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agetextfieldKeyReleased

       String PATTERN="^[0-9]{1,3}$";
      Pattern patt=Pattern.compile(PATTERN);
      Matcher match=patt.matcher(agetextfield.getText());
      if(!match.matches()){
      ageELabel.setText("Age is incorrect");
      }
      else{
          ageELabel.setText(null);
   
    }//GEN-LAST:event_agetextfieldKeyReleased
    }
    private void EmailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTextFieldKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,30}[@][a-zA-Z 0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(EmailTextField.getText());
        if(!match.matches()){
            emailELabel.setText("EMAIL is incorrect!");
        }
        else{
            emailELabel.setText(null);
        
    }//GEN-LAST:event_EmailTextFieldKeyReleased
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel ageELabel;
    private javax.swing.JTextField agetextfield;
    private javax.swing.JLabel emailELabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JTextField firstnametextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField lastnametextfield;
    private javax.swing.JLabel messagelabel;
    private javax.swing.JScrollPane messagetexta;
    private javax.swing.JTextArea messagetextarea;
    private javax.swing.JButton submit;
    private javax.swing.JPanel titleLab;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
